cmake_minimum_required(VERSION 3.10)
project(kosaraju_visualization LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
if(NOT TARGET Utils)
  add_subdirectory(../../lib "${CMAKE_CURRENT_BINARY_DIR}/lib")
endif()
if(NOT TARGET scc_algorithm)
  add_library(scc_algorithm ../scc/src/scc.cpp)
  target_include_directories(scc_algorithm PUBLIC ../scc/src)
  target_link_libraries(scc_algorithm PUBLIC Utils)
endif()
add_executable(kosaraju_visualization ../scc/src/main.cpp)
target_link_libraries(kosaraju_visualization PRIVATE scc_algorithm)

enable_testing()
find_package(GTest REQUIRED)
add_executable(kosaraju_visualization_tests ../scc/src/test.cpp)
target_link_libraries(kosaraju_visualization_tests PRIVATE scc_algorithm GTest::gtest_main)
include(GoogleTest)
gtest_discover_tests(kosaraju_visualization_tests TEST_PREFIX "kosaraju.")
